config/routes.rb
Rails.application.routes.draw do
  resources :specializations

  resources :merchants do
    resources :openings
  end

  get 'search' => "merchants#search"

  root 'merchants#home'

end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  require 'elasticsearch/model'

  attr_accessor :specialization

  has_many :openings, :dependent => :destroy
  has_and_belongs_to_many :specializations

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  Merchant.import # for auto sync model with elastic search

end

app/models/opening.rb
class Opening < ActiveRecord::Base
  belongs_to :merchant
end

app/models/specialization.rb
class Specialization < ActiveRecord::Base
  require 'elasticsearch/model'

  has_and_belongs_to_many :merchants

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  Specialization.import # for auto sync model with elastic search

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]

  def home
     @merchants = Merchant.all
     @specializations = Specialization.all
  end

  def search
    if params[:q].nil?
      @merchants = []
    else
      @specializations = Specialization.search(params[:q])
      @spec_merchants = @specializations.records.map(&:merchants)
      @search_merchants = Merchant.search(params[:q]).records
      @merchants = (@spec_merchants.first.to_a + @search_merchants).uniq
    end
    respond_to do |format|
      format.js
    end
  end

  def index
    @merchants = Merchant.all
  end

  def show
  end

  def new
    @merchant = Merchant.new
  end

  def edit
  end

  def create
    @merchant = Merchant.new(merchant_params)
      if @merchant.save
        @merchant.specializations << Specialization.where(:name => params[:merchant][:specialization])
         redirect_to merchants_path, notice: 'Merchant was successfully created.'
      else
         render :new
      end
  end

  def update
      if @merchant.update(merchant_params)
        @merchant.specializations << Specialization.where(:name => params[:merchant][:specialization])
        redirect_to merchants_path, notice: 'Merchant was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @merchant.destroy
    redirect_to merchants_url, notice: 'Merchant was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchant_params
      params.require(:merchant).permit(:name, :email, :status, :about, :gender, :price, :review_count, :avg_rating,:specialization)
    end
end

app/controllers/openings_controller.rb
class OpeningsController < ApplicationController
  before_action :set_opening, only: [:show, :edit, :update, :destroy]
  before_action :set_merchant

  def index
    @openings = @merchant.openings
  end

  def show
  end

  def new
    @opening = Opening.new
  end

  def edit
  end

  def create
    @opening = @merchant.openings.new(opening_params)

      if @opening.save
        redirect_to merchant_openings_path(@merchant), notice: 'Opening was successfully created.'
      else
        render :new
      end
  end

  def update
      if @opening.update(opening_params)
         redirect_to merchant_openings_path(@merchant), notice: 'Opening was successfully updated.'
      else
          render :edit
      end
  end

  def destroy
    @opening.destroy
    redirect_to openings_url, notice: 'Opening was successfully destroyed.'
  end

  private

    def set_merchant
      @merchant = Merchant.find(params[:merchant_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_opening
      @opening = Opening.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def opening_params
      params.require(:opening).permit(:merchant_id, :start_time, :endtime, :status)
    end
end

app/controllers/specializations_controller.rb
class SpecializationsController < ApplicationController
  before_action :set_specialization, only: [:show, :edit, :update, :destroy]

  def index
    @specializations = Specialization.all
  end

  def show
  end

  def new
    @specialization = Specialization.new
  end

  def edit
  end

  def create
    @specialization = Specialization.new(specialization_params)
      if @specialization.save
         redirect_to @specialization, notice: 'Specialization was successfully created.'
      else
         render :new
      end
  end

  def update
      if @specialization.update(specialization_params)
        redirect_to @specialization, notice: 'Specialization was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @specialization.destroy
    redirect_to specializations_url, notice: 'Specialization was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialization
      @specialization = Specialization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specialization_params
      params.require(:specialization).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/helpers/openings_helper.rb
module OpeningsHelper
end

app/helpers/specializations_helper.rb
module SpecializationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ErosApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to 'Eros App', root_path, :class => "brand" %>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Merchants", merchants_path %></li>
          <li><%= link_to "Specialization", specializations_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container">
    <%= yield %>
</div>

</body>
</html>

app/views/merchants/_form.html.erb
<%= form_for(@merchant) do |f| %>
  <% if @merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
      <% @merchant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :review_count %><br>
    <%= f.number_field :review_count %>
  </div>
  <div class="field">
    <%= f.label :avg_rating %><br>
    <%= f.text_field :avg_rating %>
  </div>
    <div class="field">
      <%= f.label :specialization %><br>
      <%= f.select :specialization, options_for_select(Specialization.all.map(&:name), Specialization.all.map(&:id)), { :prompt => "Please Select"},{ :multiple => true, :size => 5 } %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/merchants/_merchant_list.html.erb
<div>Merchants</div>

<% @merchants.each do |merchant| %>
    <div class="well" style="height:70px;">
        <div class="span5" >
          <%= merchant.name %><br/>
          <%= merchant.price %><br/>
          <%= merchant.about %><br/>
          Specializations - <%= merchant.specializations.map(&:name).join(',') %>
        </div>
        <div class="span3" >
          <% merchant.openings.each do |opening| %>
              <%= opening.start_time.strftime("%d %b %H:%M") %> -
              <%= opening.endtime.strftime("%d %b %H:%M") %><br/>
          <% end %>
        </div>
    </div>
<% end %>

app/views/merchants/edit.html.erb
<h1>Editing Merchant</h1>

<%= render 'form' %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

app/views/merchants/home.html.erb
<div class="row">
    <div style="text-align: right;">
      <%= form_tag search_path, method: :get, :remote => true do %>
          <p>
            <%= text_field_tag :q, params[:q] %>
            <%= submit_tag "Search"  %>
          </p>
      <% end %>
    </div>
    <hr/>

    <div class="span10" id="merchant_list">
      <%= render 'merchant_list' %>
    </div>
</div>

app/views/merchants/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Merchants</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Status</th>
      <th>About</th>
      <th>Gender</th>
      <th>Price</th>
      <th>Review count</th>
      <th>Avg rating</th>
      <th>Specializations</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.name %></td>
        <td><%= merchant.email %></td>
        <td><%= merchant.status %></td>
        <td><%= merchant.about %></td>
        <td><%= merchant.gender %></td>
        <td><%= merchant.price %></td>
        <td><%= merchant.review_count %></td>
        <td><%= merchant.avg_rating %></td>
        <td><%= merchant.specializations.map(&:name).join(',') %></td>
        <td><%= link_to 'Openings', merchant_openings_path(merchant) %></td>
        <td><%= link_to 'Show', merchant %></td>
        <td><%= link_to 'Edit', edit_merchant_path(merchant) %></td>
        <td><%= link_to 'Destroy', merchant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merchant', new_merchant_path %>

app/views/merchants/new.html.erb
<h1>New Merchant</h1>

<%= render 'form' %>

<%= link_to 'Back', merchants_path %>

app/views/merchants/search.js.erb
$('#merchant_list').html("<%= j render 'merchant_list' %>");

app/views/merchants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @merchant.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @merchant.email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @merchant.status %>
</p>

<p>
  <strong>About:</strong>
  <%= @merchant.about %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @merchant.gender %>
</p>

<p>
  <strong>Price:</strong>
  <%= @merchant.price %>
</p>

<p>
  <strong>Review count:</strong>
  <%= @merchant.review_count %>
</p>

<p>
  <strong>Avg rating:</strong>
  <%= @merchant.avg_rating %>
</p>

<%= link_to 'Edit', edit_merchant_path(@merchant) %> |
<%= link_to 'Back', merchants_path %>

app/views/openings/_form.html.erb
<%= form_for([@merchant,@opening]) do |f| %>
  <% if @opening.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@opening.errors.count, "error") %> prohibited this opening from being saved:</h2>

      <ul>
      <% @opening.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :endtime %><br>
    <%= f.datetime_select :endtime %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/openings/edit.html.erb
<h1>Editing Opening</h1>

<%= render 'form' %>

<%= link_to 'Back', merchant_openings_path(@merchant) %>

app/views/openings/index.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @merchant.name %>'s Openings</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Start time</th>
      <th>End Time</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @openings.each do |opening| %>
      <tr>
        <td><%= opening.start_time %></td>
        <td><%= opening.endtime %></td>
        <td><%= opening.status %></td>
        <td><%= link_to 'Show', merchant_opening_path(@merchant, opening) %></td>
        <td><%= link_to 'Edit', edit_merchant_opening_path(@merchant,opening) %></td>
        <td><%= link_to 'Destroy', merchant_opening_path(@merchant, opening), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Opening', new_merchant_opening_path(@merchant) %>

app/views/openings/new.html.erb
<h1>New Opening</h1>

<%= render 'form' %>

<%= link_to 'Back', merchant_openings_path(@merchant) %>

app/views/openings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Merchant:</strong>
  <%= @opening.merchant_id %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @opening.start_time %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @opening.endtime %>
</p>

<p>
  <strong>Status:</strong>
  <%= @opening.status %>
</p>

<%= link_to 'Edit', edit_opening_path(@opening) %> |
<%= link_to 'Back', openings_path %>

app/views/specializations/_form.html.erb
<%= form_for(@specialization) do |f| %>
  <% if @specialization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@specialization.errors.count, "error") %> prohibited this specialization from being saved:</h2>

      <ul>
      <% @specialization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specializations/edit.html.erb
<h1>Editing Specialization</h1>

<%= render 'form' %>

<%= link_to 'Show', @specialization %> |
<%= link_to 'Back', specializations_path %>

app/views/specializations/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Specializations</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specializations.each do |specialization| %>
      <tr>
        <td><%= specialization.name %></td>
        <td><%= link_to 'Show', specialization %></td>
        <td><%= link_to 'Edit', edit_specialization_path(specialization) %></td>
        <td><%= link_to 'Destroy', specialization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Specialization', new_specialization_path %>

app/views/specializations/new.html.erb
<h1>New Specialization</h1>

<%= render 'form' %>

<%= link_to 'Back', specializations_path %>

app/views/specializations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @specialization.name %>
</p>

<%= link_to 'Edit', edit_specialization_path(@specialization) %> |
<%= link_to 'Back', specializations_path %>